bait_list = {
	{
		id = "any",
		ui_name = "Any",
	},	
	{
		id = "COMMON_GRUB",
		ui_name = "Common Grub",
		ui_description = "Standard bait for your fishing needs.",
		sprite = "mods/fishing/files/baits/gfx/common_grub.png",
		sprite_small = "mods/fishing/files/baits/gfx/common_grub_small.png",
		max_uses = 10,
		price = 50,
	},
	{
		id = "SPICY_BURRITO",
		ui_name = "Spicy Burrito",
		ui_description = "Some fish seem to really like this bait.",
		sprite = "mods/fishing/files/baits/gfx/burrito.png",
		sprite_small = "mods/fishing/files/baits/gfx/burrito_small.png",
		max_uses = 5,
		price = 150,
	},
	{
		id = "STEAK",
		ui_name = "Steak",
		ui_description = "A very good looking steak, too bad it is for catching fish.",
		sprite = "mods/fishing/files/baits/gfx/steak.png",
		sprite_small = "mods/fishing/files/baits/gfx/steak_small.png",
		max_uses = 3,
		price = 150,
	},
	{
		id = "FISH_STICK",
		ui_name = "Fish Stick",
		ui_description = "A tasty fish stick.",
		sprite = "mods/fishing/files/baits/gfx/fish_stick.png",
		sprite_small = "mods/fishing/files/baits/gfx/fish_stick_small.png",
		max_uses = 5,
		price = 250,
	},
}
